version: "3.7"

services:

  # Nginx
  nginx:
    container_name: test_nginx
    image: merlinface.dev/test_nginx
    restart: always
    build:
      context: docker/nginx
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: '1.0'
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - "18109:443"
